runtime: python37

handlers:
- url: /.*
  script: auto

env_variables:
  LOGGING_LEVEL: "10"
  LOGGING_FORMAT: "%(asctime)s %(levelname)s: %(message)s"
  # PERSISTER: '{"engine_name": "redis", "parameters": {"host": "localhost", "port": 6379, "db": 0, "password": ""}}'
  PERSISTER: '{"engine_name": "gaestorage", "parameters": {"bucket": "dasander-cowbull-save-games"}}'
  # PERSISTER: '{"engine_name": "gcpdatastore", "parameters": {}}'
