runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.*
  script: app.app

env_variables:
  OLD_COWBULL_CONFIG: "config/cowbull.cfg"
  REDIS_HOST: "redis-11039.c8.us-east-1-2.ec2.cloud.redislabs.com"
  REDIS_PORT: "11039"
  LOGGING_LEVEL: "10"
  LOGGING_FORMAT: "%(asctime)s %(levelname)s: %(message)s"
