steps:
- name: 'python:3.8.2-buster'
  args: [
    '/bin/sh',
    './cloudbuild_test.sh'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/cowbull:${_BUILD_NUMBER}', 
    '-f',
    'vendor/docker/Dockerfile',
    '.' 
  ]
substitutions:
  _BUILD_NUMBER: "20.04-37"
images:
- 'gcr.io/$PROJECT_ID/cowbull:${_BUILD_NUMBER}'
