steps:
- name: 'python:3.8.2-buster'
  args: [
    '/bin/sh',
    './cloudbuild_test.sh'
  ]
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --cache=true
  - --cache-ttl=24h
  - --destination=gcr.io/$PROJECT_ID/cowbull:${_BUILD_NUMBER}
  - --dockerfile=vendor/docker/Dockerfile
substitutions:
  _BUILD_NUMBER: "20.04-41"
