version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: redis
        name: redis

    working_directory: ~/python_cowbull_server

    environment:
      - REDIS_HOST: localhost
      - REDIS_PORT: 6379

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest -v tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
