version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: redis

    working_directory: ~/python_cowbull_server

    environment:
      - PERSISTER: '{"engine_name": "redis", "parameters": {"host": "localhost", "port": 6379, "db": 0}}'

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip2 install -r requirements.txt

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            set -o pipefail
            python -m unittest -v tests 2> >(tee -a /tmp/unittest-report.log >&2)

      - setup_remote_docker

      - run:
          name: build docker image
          command: |
            docker login --username=$doclog --password=$docpass
            docker build -f vendor/docker/Dockerfile -t dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .
            docker run --name redis -d redis
            docker run --name test2 --link redis
              -e PERSISTER='{"engine_name": "redis", "parameters": {"host": "redis"}' \
              -d dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM \
              python -m unittest -v

      - run:
          name: install Google Cloud dependencies
          command: |
            # Fix the repo to Jessie - needs to be updated later
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            export CLOUD_SDK_REPO="cloud-sdk-jessie"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk --yes
            echo $circlecibuilder | base64 --decode --ignore-garbage > auth.json
            gcloud auth activate-service-account $circleciuser --key-file auth.json --project=$gproject

      - run:
          name: Build GAE project and deploy
          command: |
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            mkdir -p vendor/gae
            pip2 install -t vendor/gae/lib -r requirements.txt
            gcloud app deploy --version="cigen-"$MAJOR_VERSION"-"$MINOR_VERSION"-"$CIRCLE_BUILD_NUM --quiet

      - run:
          name: push docker image
          command: |
            docker tag dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM dsanderscan/$IMAGE_NAME:latest
            docker push dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push dsanderscan/$IMAGE_NAME:latest
      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: /tmp/unittest-report.log
          destination: unittest-report