version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: redis
        name: redis

    working_directory: ~/python_cowbull_server

    environment:
      - REDIS_HOST: localhosty
      - REDIS_PORT: 6379

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            set -o pipefail
            python -m unittest -v tests 2> >(tee -a /tmp/unittest-report.log >&2)

      - run:
          name: install Google Cloud dependencies
          command: |
            # Fix the repo to Jessie - needs to be updated later
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            export CLOUD_SDK_REPO="cloud-sdk-jessie"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk --yes
            echo $circlecibuilder | base64 --decode --ignore-garbage > auth.json
            gcloud auth activate-service-account $circleciuser --key-file auth.json --project=$gproject

      - run:
          name: Build GAE project and deploy
          command: |
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            mkdir -p vendor/gae
            pip install -t vendor/gae/lib -r requirements.txt
            gcloud app deploy --quiet

      - setup_remote_docker

      - run:
          name: build docker image
          command: |
            docker login --username=$doclog --password=$docpass
            docker build -f vendor/docker/Dockerfile -t dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .

      - run:
          name: push docker image
          command: |
            docker tag dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM dsanderscan/test_cowbull:latest
            docker push dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push dsanderscan/test_cowbull:latest

      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: /tmp/unittest-report.log
          destination: unittest-report
