version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/python_cowbull_server

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - setup_remote_docker

      - run:
          name: Docker login
          command: |
            docker login --username=$doclog --password=$docpass

      - run:
          name: Docker up and build
          command: |
            docker-compose -f vendor/docker/docker-compose-cicd.yml up -d --build

      - run:
          name: Unit tests with Redis
          command: |
            docker exec -it docker_cowbull_svc_1 \
              bash -c "python -m unittest -v tests 2> >(tee -a /tmp/dockertest-report.log >&2)"
            docker cp docker_cowbull_svc_1:/tmp/dockertest-report.log /tmp/dockertest-report.log

      - run:
          name: Build final Docker image
          command: |
            docker build -f vendor/docker/Dockerfile -t $doclog/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .

      - deploy:
          name: Push docker image
          command: |
            docker tag $doclog/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM $doclog/$IMAGE_NAME:latest
            docker push $doclog/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push $doclog/$IMAGE_NAME:latest

      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: /tmp/dockertest-report.log
          destination: dockertest-report
