version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: redis
        name: redis

    working_directory: ~/python_cowbull_server

    environment:
      - REDIS_HOST: localhost
      - REDIS_PORT: 6379

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - setup_remote_docker

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: v2-dependencies-{{ "requirements.txt" }}
          paths:
            - ~/.m2

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest -v tests

      - run:
          name: build docker image
          command: |
            docker login --username=$doclog --password=$docpass
            docker build -f vendor/docker/Dockerfile -t dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .
      - run:
          name: push docker image
          command: |
            docker tag dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM dsanderscan/test_cowbull:latest
            docker push dsanderscan/test_cowbull:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push dsanderscan/test_cowbull:latest

      - store_artifacts:
          path: test-reports
          destination: test-reports
